image: bradrydzewski/base
script:
  - echo hello world
  - bash -x .drone/build.sh
  - docker images
  - docker ps -a
  - docker build -t drone_build_test:1
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#cirle_ci'
    on_started: false
    on_success: true
    on_failure: true