image: test:2
script:
  - bash -x .drone/build.sh
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#cirle_ci'
    on_started: false
    on_success: false
    on_failure: false