image: http://my-docker-registry/my-docker-image:version
script:
  - ./.drone/build.sh
deploy:
  bash:
    script:
      - ./drone/deploy.sh
notify:
  email:
    recipients:
      - jacek.lawniczak@schibsted.pl