image: bradrydzewski/base
script:
  - echo hello world
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#cirle_ci'
    on_started: true
    on_success: true
    on_failure: true